name: dart_sort_queue
description: A tiny queue that sorts its items
version: 0.0.2+3
homepage: https://github.com/dartclub/dart_sort_queue

environment:
  sdk: ">=2.17.5 <3.0.0"

dev_dependencies:
  dartclub_lint: ^0.4.2
  test: ^1.16.0

dependencies:
  collection: ^1.16.0
