name: dart_sort_queue
description: A tiney queue that sorts its items
version: 1.0.0
# homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: { collection: ^1.16.0 }
